// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetBootstrapData, GetBootstrapResponses, GetHealthData, GetHealthResponses, GetTokensLocaleData, GetTokensLocaleResponses, PostBlameData, PostBlameResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * assigns blame to the current user
 */
export const postBlame = <ThrowOnError extends boolean = false>(options?: Options<PostBlameData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostBlameResponses, unknown, ThrowOnError>({
        url: '/blame',
        ...options
    });
};

/**
 * retrieves the live configuration and language tokens for the client
 */
export const getBootstrap = <ThrowOnError extends boolean = false>(options?: Options<GetBootstrapData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetBootstrapResponses, unknown, ThrowOnError>({
        url: '/bootstrap',
        ...options
    });
};

/**
 * indicates whether the server is running
 */
export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetHealthResponses, unknown, ThrowOnError>({
        url: '/health',
        ...options
    });
};

/**
 * retrieves the language tokens for a given locale
 */
export const getTokensLocale = <ThrowOnError extends boolean = false>(options: Options<GetTokensLocaleData, ThrowOnError>) => {
    return (options.client ?? client).get<GetTokensLocaleResponses, unknown, ThrowOnError>({
        url: '/tokens/:locale',
        ...options
    });
};
