// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api` | (string & {});
};

export type GetAdminSitesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/sites';
};

export type GetAdminSitesResponses = {
    /**
     * found a list of sites
     */
    200: {
        sites: Array<{
            id: string;
            name: string;
            defaultLocale: string;
            configuredLocales: Array<string>;
        }>;
    };
};

export type GetAdminSitesResponse = GetAdminSitesResponses[keyof GetAdminSitesResponses];

export type PostClientBlameData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/client/blame';
};

export type PostClientBlameResponses = {
    /**
     * successfully assigned blame
     */
    201: unknown;
};

export type GetClientBootstrapData = {
    body?: never;
    path?: never;
    query?: {
        locale?: string;
    };
    url: '/client/bootstrap';
};

export type GetClientBootstrapErrors = {
    /**
     * unable to retrieve site retrieved configurations
     */
    400: unknown;
};

export type GetClientBootstrapResponses = {
    /**
     * successfully retrieved site configurations
     */
    200: {
        availableLocales: Array<string>;
        defaultLocale: string;
        tokens: {
            [key: string]: string;
        };
    };
};

export type GetClientBootstrapResponse = GetClientBootstrapResponses[keyof GetClientBootstrapResponses];

export type GetClientTokensByLocaleData = {
    body?: never;
    path: {
        locale: string;
    };
    query?: never;
    url: '/client/tokens/{locale}';
};

export type GetClientTokensByLocaleErrors = {
    /**
     * unable to retrieve tokens for locale
     */
    404: unknown;
};

export type GetClientTokensByLocaleResponses = {
    /**
     * successfully retrieved tokens
     */
    200: {
        tokens: {
            [key: string]: string;
        };
    };
};

export type GetClientTokensByLocaleResponse = GetClientTokensByLocaleResponses[keyof GetClientTokensByLocaleResponses];

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * successfully retrieved configurations
     */
    200: unknown;
};
