// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api` | (string & {});
};

export type PostBlameData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/blame';
};

export type PostBlameResponses = {
    /**
     * successfully assigned blame
     */
    201: unknown;
};

export type GetBootstrapData = {
    body?: never;
    path?: never;
    query?: {
        locale?: string;
    };
    url: '/bootstrap';
};

export type GetBootstrapErrors = {
    /**
     * unable to retrieve site retrieved configurations
     */
    400: unknown;
};

export type GetBootstrapResponses = {
    /**
     * successfully retrieved site configurations
     */
    200: {
        availableLocales: Array<string>;
        defaultLocale: string;
        tokens: {
            [key: string]: string;
        };
    };
};

export type GetBootstrapResponse = GetBootstrapResponses[keyof GetBootstrapResponses];

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * successfully retrieved configurations
     */
    200: unknown;
};

export type GetTokensByLocaleData = {
    body?: never;
    path: {
        locale: string;
    };
    query?: never;
    url: '/tokens/{locale}';
};

export type GetTokensByLocaleErrors = {
    /**
     * unable to retrieve tokens for locale
     */
    404: unknown;
};

export type GetTokensByLocaleResponses = {
    /**
     * successfully retrieved tokens
     */
    200: {
        tokens: {
            [key: string]: string;
        };
    };
};

export type GetTokensByLocaleResponse = GetTokensByLocaleResponses[keyof GetTokensByLocaleResponses];
